const LIST_VIEW_ITEMS_COUNT = 3;
const VUEX_PERSIST_KEY = "memoNotes";
const NEW_NOTE_KEY = "new";
const MAX_MUTATION_STACK_SIZE = 512;
const MAX_NOTE_TITLE_LENGTH = 256;
const SHORT_TITLE_LENGTH = 44;
const MAX_TODO_TEXT_LENGTH = 128;
const SHORT_TEXT_LENGTH = 50;
const MAX_TODO_ITEMS_COUNT = 32;
const KEYBOARD_CODES = {
  escape: 27
};

export {
  NEW_NOTE_KEY,
  LIST_VIEW_ITEMS_COUNT,
  VUEX_PERSIST_KEY,
  KEYBOARD_CODES,
  MAX_NOTE_TITLE_LENGTH,
  SHORT_TITLE_LENGTH,
  MAX_TODO_TEXT_LENGTH,
  SHORT_TEXT_LENGTH,
  MAX_TODO_ITEMS_COUNT,
  MAX_MUTATION_STACK_SIZE
};
