const LIST_VIEW_ITEMS_COUNT = 3;

const VUEX_PERSIST_KEY = "memoNotes";

const NEW_NOTE_KEY = "new";

const EDIT = "EDIT_NOTE";

const MAX_MUTATION_STACK_SIZE = 512;

const KEYBOARD_CODES = {
  enter: 13,
  escape: 27
};

export {
  NEW_NOTE_KEY,
  LIST_VIEW_ITEMS_COUNT,
  VUEX_PERSIST_KEY,
  KEYBOARD_CODES,
  EDIT,
  MAX_MUTATION_STACK_SIZE
};
