const LIST_VIEW_ITEMS_COUNT = 3;
const VUEX_PERSIST_KEY = "memoNotes";
const NEW_NOTE_KEY = "new";
const EDIT_NOTE_MUTATION = "EDIT_NOTE";
const MAX_MUTATION_STACK_SIZE = 512;
const MAX_NOTE_TITLE_LENGTH = 256;
const MAX_TODO_TEXT_LENGTH = 64;
const KEYBOARD_CODES = {
  enter: 13,
  escape: 27
};

export {
  NEW_NOTE_KEY,
  LIST_VIEW_ITEMS_COUNT,
  VUEX_PERSIST_KEY,
  KEYBOARD_CODES,
  EDIT_NOTE_MUTATION,
  MAX_NOTE_TITLE_LENGTH,
  MAX_TODO_TEXT_LENGTH,
  MAX_MUTATION_STACK_SIZE
};
